apiVersion: apps/v1
kind: Deployment
metadata:
  name: "demo-6595"
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demo-6595"
  template:
    metadata:
      labels:
        app: "demo-6595"
    spec:
      containers:
        - name: "demo-6595"
          image: "czwartekaks.azurecr.io/demo"
          ports:
          - containerPort: 8080
